version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to AWS CodeArtifact...
      - CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain devops-domain-project --domain-owner 817952731382 --region us-east-1 --query authorizationToken --output text`
      - export CODEARTIFACT_AUTH_TOKEN
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -s settings.xml
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - chmod +x scripts/*.sh  # IMPORTANT: Fixes permissions before zipping
      - mvn package -s settings.xml

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - target/devops-web-project.war
  discard-paths: no

